apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lferrazzini95/arr-helm.git'
    targetRevision: HEAD
    path: .
    helm:
      values: |
        image:
          name: fallenbagel/jellyseerr
          tag: latest

        ports:
          webui: 5055

        storage:
          config:
            size: 5Gi
            path: /app/config
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
