apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lferrazzini95/jellyfin-helm.git'
    targetRevision: HEAD
    path: .
    helm:
      values: |
        storage:
          configSize: 50Gi

        resources:
          limits:
            memory: 12Gi
            cpu: 1
            gpu.intel.com/i915: 1
          requests:
            memory: 1Gi
            cpu: 200m
            gpu.intel.com/i915: 1

        mounts:
        - pvcName: media-library-pvc
          mountName: media-library-media
          path: media

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
