apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lferrazzini95/arr-helm.git'
    targetRevision: HEAD
    path: .
    helm:
      values: |
        image:
          name: linuxserver/prowlarr
          tag: latest

        ports:
          webui: 9696

        storage:
          configSize: 5Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
