apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lferrazzini95/arr-helm.git'
    targetRevision: HEAD
    path: .
    helm:
      values: |
        image:
          name: linuxserver/radarr
          tag: latest

        ports:
          webui: 7878

        mounts:
        - pvcName: media-library-pvc
          mountName: media-library-media
          path: media

        storage:
          configSize: 5Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
