apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lferrazzini95/arr-helm.git'
    targetRevision: HEAD
    path: .
    helm:
      values: |
        image:
          name: linuxserver/radarr
        storage:
          configSize: 5Gi
          mediaPVC: media-library-pvc
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
