apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lferrazzini95/arr-helm.git'
    targetRevision: HEAD
    path: .
    helm:
      values: |
        image:
          name: linuxserver/sabnzbd
          tag: latest

        ports:
          webui: 8080

        storage:
          configSize: 25Gi
          media:
            name: media-library-pvc
            path: tvshows
        resources:
          limits:
            memory: 4096Mi
            cpu: 4
          requests:
            memory: 512Mi
            cpu: 500m

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
